### ISSUE TITLE
Filters by numeric folder names only

### ISSUE THREAD

**Issue by AiTLachlan** [TheGuyThatMonitors/start#1]
This section:
```ps
$numDirs = Get-ChildItem -Path $dataDir -Attributes D | 
            Where-Object { $_.Name -match '^\d+$' } | 
            Sort-Object
```
The `Where-Object { $_.Name -match '^\d+$' }` section is filtering all folder names to only include folders whose names are exclusively numbers.

You can just do this:
```ps
$numDirs = Get-ChildItem -Path $dataDir -Attributes D | Sort-Object
```

**Comment by TheGuyThatMonitors** [comment]
Coder has been updated, stil not resolved.
